
package by.htp.example.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ws/meal", targetNamespace = "http://soap.ws.example.htp.by/", wsdlLocation = "http://localhost:8080/ws/meal?wsdl")
public class Ws_002fMeal
    extends Service
{

    private final static URL WS_002FMEAL_WSDL_LOCATION;
    private final static WebServiceException WS_002FMEAL_EXCEPTION;
    private final static QName WS_002FMEAL_QNAME = new QName("http://soap.ws.example.htp.by/", "ws/meal");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/meal?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WS_002FMEAL_WSDL_LOCATION = url;
        WS_002FMEAL_EXCEPTION = e;
    }

    public Ws_002fMeal() {
        super(__getWsdlLocation(), WS_002FMEAL_QNAME);
    }

    public Ws_002fMeal(WebServiceFeature... features) {
        super(__getWsdlLocation(), WS_002FMEAL_QNAME, features);
    }

    public Ws_002fMeal(URL wsdlLocation) {
        super(wsdlLocation, WS_002FMEAL_QNAME);
    }

    public Ws_002fMeal(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WS_002FMEAL_QNAME, features);
    }

    public Ws_002fMeal(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Ws_002fMeal(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapMealService
     */
    @WebEndpoint(name = "SoapMealServicePort")
    public SoapMealService getSoapMealServicePort() {
        return super.getPort(new QName("http://soap.ws.example.htp.by/", "SoapMealServicePort"), SoapMealService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapMealService
     */
    @WebEndpoint(name = "SoapMealServicePort")
    public SoapMealService getSoapMealServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.ws.example.htp.by/", "SoapMealServicePort"), SoapMealService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WS_002FMEAL_EXCEPTION!= null) {
            throw WS_002FMEAL_EXCEPTION;
        }
        return WS_002FMEAL_WSDL_LOCATION;
    }

}
